### PR TITLE
Fix compiling on MacOSX m1 arch

### PR DESCRIPTION
**Pull request by zhentao-huang**
Signed-off-by: Zhentao Huang <zhentao_huang@hotmail.com>

### Platform
* OS : MacOSX 12.6.1
* SDK : MacOSX 13.0
* autoconf : 2.71
* automake : 1.16.5
* compiler : apple clang 14.0.0

### Issue 
zlog is not able to pass compiling on MacOSX with SDK 13.0( either with 11.3 or 12.3)
```
../../src/event.c:97:5: error: implicit declaration of function 'pthread_threadid_np' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    pthread_threadid_np(NULL, &tid64);
```
### Root Cause
1. In MacOSX sdks `pthread/phtread.h` wrapped declaration of `pthread_thread_np` with a condition listed below
```
#if (!defined(_POSIX_C_SOURCE) && !defined(_XOPEN_SOURCE)) || defined(_DARWIN_C_SOURCE) || defined(__cplusplus) // line 520, OSX sdk 13.0
...
int pthread_threadid_np(pthread_t _Nullable,__uint64_t* _Nullable);  // line 527, OSX sdk 13.0
#else
...

```
2. `fmacro.h` defined `_XOPEN_SOURCE` in line 14

These two prevents `pthread_threadid_np` being declared. So error occured.

### Fix 
To minimize effect the fix just bypasses `_XOPEN_SOURCE` declaration via macro `__APPLE__`

### CODE REVIEW

**Comment by bmanojlovic** [comment]
please raise issue on original repository [HardySimpson/zlog](https://github.com/HardySimpson/zlog)
as this repository is just autoconf set of addons, and i will pull from upstream corrected version

**Comment by zhentao-huang** [comment]
The issue had been fixed in original repo by [this commit]
(https://github.com/HardySimpson/zlog/commit/cd40f93b2c080d112284a2fbf7b3cc783724f521).  

By defining `_DARWIN_C_SOURCE`, it made `pthread_threadid_np` visiable. 
So I do same approch to fix it.

**Comment by bmanojlovic** [comment]
as mentioned i have already pulled latest changes and as such you should have correct version if you use this repository

**Comment by zhentao-huang** [comment]
Hi, my fix had been merged in the main repo. 
I'd like to do re-check after you sync with it. 

BR and thanks
zhentao

**Comment by bmanojlovic** [comment]
can you confirm it is synced correctly

**Comment by zhentao-huang** [comment]
Yes, it’s fixed


2022年11月23日 00:26，Boris Manojlovic ***@***.******@***.***>> 写道：



can you confirm it is synced correctly

**Pull request closed without merging**
